package design;

import SqlDatabase.HerokuCalendarPermitSqlConnection;
import SqlDatabase.HerokuCalendarSqlConnection;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author Leyre
 */
public class InputCalendarName extends javax.swing.JDialog implements usuario{

    /**
     * Creates new form InputCalendarName
     */
    private int id_cal_recien_creado;
    private boolean calendarExist=false;
    public User userSignedIn;
    private boolean help=false;
    private User userSignedUpmp;
    
    public InputCalendarName(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public InputCalendarName(){
        initComponents();
        Color color = new Color(255,255,255);
        this.getContentPane().setBackground(color);
        setModal(true);
        this.setLocationRelativeTo(null);
        userSignedUpmp=userSigned;
        changeColor();
    }
    
    public void changeColor(){
        if(userSignedUpmp.getModo() == 1){
            jPanel1.setBackground(Color.decode("#000000"));
            calendarName.setForeground(Color.decode("#FFFFFF"));
            calendarName.setBackground(Color.decode("#9EB8C2"));
            AddCalendar.setBackground(Color.decode("#859EBC"));
            jLabel1.setBackground(Color.decode("#CBEFFF"));
            jLabel1.setForeground(Color.decode("#FFFFFF"));
        }else{
            jPanel1.setBackground(Color.decode("#FFFFFF"));
            calendarName.setForeground(Color.decode("#000000"));
            calendarName.setBackground(Color.decode("#FFFFFF"));
            AddCalendar.setBackground(Color.decode("#66CCFF"));
            jLabel1.setBackground(Color.decode("#FFFFFF"));
            jLabel1.setForeground(Color.decode("#000000"));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        calendarName = new javax.swing.JTextField();
        AddCalendar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel1.setText("Enter the name of your calendar");

        AddCalendar.setBackground(new java.awt.Color(102, 204, 255));
        AddCalendar.setText("Add");
        AddCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCalendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calendarName, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        
    public int getIdCalendarCreated(){
        return this.id_cal_recien_creado;
    }
    public boolean getCalendarExists(){
        return this.calendarExist;
    }
    
    public boolean gethelp(){
        return this.help;
    }
    
    private void AddCalendarActionPerformed(java.awt.event.ActionEvent evt) { 
        String CalendarName = this.calendarName.getText();
        HerokuCalendarPermitSqlConnection conex_cal_per = HerokuCalendarPermitSqlConnection.getInstance();
        HerokuCalendarSqlConnection conex_cal = HerokuCalendarSqlConnection.getInstance();
        String new_email_id=CalendarName.trim()+userSignedIn.getEmail();
        /*control para que no se cree otro calendario, si ya existe otro con el mismo id*/
        boolean verdadero=conex_cal.selectCalendarIdBySpecialId(new_email_id);
        if(verdadero == true){
            this.calendarExist=true;
            JOptionPane.showMessageDialog(null, "El calendario no se ha podido crear porque ya existe uno con el mismo nombre");
        }else{
            System.out.println("Se procede a crear el nuevo calendario");
            conex_cal.insertCalendar(CalendarName,new_email_id);
            id_cal_recien_creado=conex_cal.getCalendar(new_email_id);
            System.out.println("id cal recien creado"+id_cal_recien_creado);
            if(id_cal_recien_creado >0)
                conex_cal_per.insertCalendarPermitTaskNull(userSignedIn.getId(), id_cal_recien_creado, "Admin");
        }
        this.setVisible(false);
        this.help=true;
    }                                   

    private void AddCalendarKeyPressed(java.awt.event.KeyEvent evt) {                                       
        String CalendarName = calendarName.getText();
        HerokuCalendarPermitSqlConnection conex_cal_per = HerokuCalendarPermitSqlConnection.getInstance();
        HerokuCalendarSqlConnection conex_cal = HerokuCalendarSqlConnection.getInstance();
        String new_email_id=CalendarName+userSignedIn.getEmail();
        conex_cal.insertCalendar(CalendarName,new_email_id);
        id_cal_recien_creado=conex_cal.getCalendar(new_email_id);
        if(id_cal_recien_creado >0)
            conex_cal_per.insertCalendarPermitTaskNull(userSignedIn.getId(), id_cal_recien_creado, "Admin");
           this.setVisible(false);
    }                                      


    
    
    public String getCalendarName(){
        return calendarName.getText();
    }
    
    public int getCalendarId(){
        return id_cal_recien_creado;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputCalendarName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            InputCalendarName dialog = new InputCalendarName(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddCalendar;
    private javax.swing.JTextField calendarName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
